services:
  db:
    build: .
    container_name: dba-challenge-db
    ports:
      - "8082:8082"   # H2 Web Console
      - "9092:9092"   # H2 TCP server (JDBC)
    volumes:
      - h2-data:/opt/h2-data

volumes:
  h2-data:
